In [31]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df =pd.read_csv("clean_bike_data.csv")
df.drop('Unnamed: 0',axis=1,inplace=True)

In [32]:
import sklearn

In [33]:
#df.column
x=df.drop('price',axis=1)
y=df[['price']]

In [34]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [35]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(5844, 5) (1462, 5) (5844, 1) (1462, 1)

## LinearRegression

In [36]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [37]:
pred = lr.predict(x_test)

In [38]:
pred[0]

array([79537.99347048])

In [39]:
y_test

         price
7062  125000.0
4553  220000.0
6505   16900.0
1918   58000.0
5227   58000.0
...        ...
2045   25000.0
527   140000.0
1783  156000.0
5065  118000.0
565    36000.0

[1462 rows x 1 columns]

## svm

In [40]:
from sklearn.svm import SVC,SVR
sv_bike=SVC()

In [41]:
sv_bike.fit(x_train,y_train)

c:\Users\RIya\Desktop\6month-Data-Science\boss\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC()

In [42]:
pred=sv_bike.predict(x_test)

In [43]:
pred

array([35000., 65000., 25000., ..., 90000., 90000., 90000.], shape=(1462,))

In [44]:
print("accuracy of test data :-",sv_bike.score(x_test,y_test)*100)
print("accuracy of train data :-",sv_bike.score(x_train,y_train)*100)

accuracy of test data :- 2.80437756497948
accuracy of train data :- 3.199863107460643

In [45]:
y_test

         price
7062  125000.0
4553  220000.0
6505   16900.0
1918   58000.0
5227   58000.0
...        ...
2045   25000.0
527   140000.0
1783  156000.0
5065  118000.0
565    36000.0

[1462 rows x 1 columns]

# Decision Tree (DT)

In [46]:
from sklearn.tree import DecisionTreeClassifier

In [47]:
dt=DecisionTreeClassifier()
dt.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [48]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [49]:
print("training accuracy :-", dt.score(x_train,y_train))
print("testing accuracy :-", dt.score(x_test,y_test))

training accuracy :- 0.9476386036960985
testing accuracy :- 0.03488372093023256

In [50]:
# with parameter
from sklearn.tree import DecisionTreeClassifier
dt_with_para =DecisionTreeClassifier(criterion='log_loss',min_samples_split=3,min_samples_leaf=2)

In [51]:
dt_with_para.fit(x_train,y_train)

DecisionTreeClassifier(criterion='log_loss', min_samples_leaf=2,
                       min_samples_split=3)

In [52]:
print("training accuracy :-",dt_with_para.score(x_train,y_train))
print("testing accuracy :-",dt_with_para.score(x_test,y_test))

training accuracy :- 0.4690280629705681
testing accuracy :- 0.030779753761969904

## Save ML model

In [53]:
import joblib
joblib.dump(dt_with_para,"dt_bike_sytem_model.lb")

['dt_bike_sytem_model.lb']

In [54]:
model=joblib.load("dt_bike_sytem_model.lb")

In [55]:
model.predict(x_test)

array([100000., 190000.,  15000., ..., 129500.,  90000.,  65000.],
      shape=(1462,))

In [57]:
model.predict([[17654.0,1,3.0,110.0,1]])

c:\Users\RIya\Desktop\6month-Data-Science\boss\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([36500.])

In [58]:
model.predict([[11000.0,1,4.0,350.0,2]])

c:\Users\RIya\Desktop\6month-Data-Science\boss\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([119900.])

In [60]:
model.predict([[10800.0,1,8.0,150.0,5]])

c:\Users\RIya\Desktop\6month-Data-Science\boss\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([35000.])