In [116]:
import numpy as np
import pandas as pd
import os

In [117]:
student_data = {
    "Student_ID": [
        101, 102, 103, 104, 105,
        106, 107, 108, 109, 110,
        111, 112, 113, 114, 115,
        116, 117, 118, 119, 120
    ],
    
    "Student_Name": [
        "Aarav", "Vivaan", "Aditya", "Krishna", "Arjun",
        "Rohan", "Karan", "Rahul", "Mohit", "Ankit",
        "Priya", "Neha", None, "Sneha", "Riya",
        "Simran", "Kavya", "Aarav", None, "Aditi"
    ],
    
    "Marks": [
        85, 78, 92, 88, 76,
        81, None, 67, 89, 73,
        91, 84, 79, 87, 93,
        75, 82, 85, None, 80
    ]
}

In [118]:
df=pd.DataFrame(student_data)

In [119]:
df  ## student_id, student_name, marks is columns name

    Student_ID Student_Name  Marks
0          101        Aarav   85.0
1          102       Vivaan   78.0
2          103       Aditya   92.0
3          104      Krishna   88.0
4          105        Arjun   76.0
5          106        Rohan   81.0
6          107        Karan    NaN
7          108        Rahul   67.0
8          109        Mohit   89.0
9          110        Ankit   73.0
10         111        Priya   91.0
11         112         Neha   84.0
12         113          NaN   79.0
13         114        Sneha   87.0
14         115         Riya   93.0
15         116       Simran   75.0
16         117        Kavya   82.0
17         118        Aarav   85.0
18         119          NaN    NaN
19         120        Aditi   80.0

In [120]:
df['Student_Name']

0       Aarav
1      Vivaan
2      Aditya
3     Krishna
4       Arjun
5       Rohan
6       Karan
7       Rahul
8       Mohit
9       Ankit
10      Priya
11       Neha
12        NaN
13      Sneha
14       Riya
15     Simran
16      Kavya
17      Aarav
18        NaN
19      Aditi
Name: Student_Name, dtype: str

In [121]:
df[['Student_Name']]

   Student_Name
0         Aarav
1        Vivaan
2        Aditya
3       Krishna
4         Arjun
5         Rohan
6         Karan
7         Rahul
8         Mohit
9         Ankit
10        Priya
11         Neha
12          NaN
13        Sneha
14         Riya
15       Simran
16        Kavya
17        Aarav
18          NaN
19        Aditi

In [122]:
df

    Student_ID Student_Name  Marks
0          101        Aarav   85.0
1          102       Vivaan   78.0
2          103       Aditya   92.0
3          104      Krishna   88.0
4          105        Arjun   76.0
5          106        Rohan   81.0
6          107        Karan    NaN
7          108        Rahul   67.0
8          109        Mohit   89.0
9          110        Ankit   73.0
10         111        Priya   91.0
11         112         Neha   84.0
12         113          NaN   79.0
13         114        Sneha   87.0
14         115         Riya   93.0
15         116       Simran   75.0
16         117        Kavya   82.0
17         118        Aarav   85.0
18         119          NaN    NaN
19         120        Aditi   80.0

In [123]:
df.head()

   Student_ID Student_Name  Marks
0         101        Aarav   85.0
1         102       Vivaan   78.0
2         103       Aditya   92.0
3         104      Krishna   88.0
4         105        Arjun   76.0

In [124]:
df.head(10)

   Student_ID Student_Name  Marks
0         101        Aarav   85.0
1         102       Vivaan   78.0
2         103       Aditya   92.0
3         104      Krishna   88.0
4         105        Arjun   76.0
5         106        Rohan   81.0
6         107        Karan    NaN
7         108        Rahul   67.0
8         109        Mohit   89.0
9         110        Ankit   73.0

In [125]:
df.tail()

    Student_ID Student_Name  Marks
15         116       Simran   75.0
16         117        Kavya   82.0
17         118        Aarav   85.0
18         119          NaN    NaN
19         120        Aditi   80.0

In [126]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_ID    20 non-null     int64
 1   Student_Name  18 non-null     str
 2   Marks         18 non-null     float64
dtypes: float64(1), int64(1), str(1)
memory usage: 612.0 bytes

In [127]:
df.columns

Index(['Student_ID', 'Student_Name', 'Marks'], dtype='str')

In [128]:
df[['Student_Name']]

   Student_Name
0         Aarav
1        Vivaan
2        Aditya
3       Krishna
4         Arjun
5         Rohan
6         Karan
7         Rahul
8         Mohit
9         Ankit
10        Priya
11         Neha
12          NaN
13        Sneha
14         Riya
15       Simran
16        Kavya
17        Aarav
18          NaN
19        Aditi

In [129]:
df[['Student_ID']]

    Student_ID
0          101
1          102
2          103
3          104
4          105
5          106
6          107
7          108
8          109
9          110
10         111
11         112
12         113
13         114
14         115
15         116
16         117
17         118
18         119
19         120

In [130]:
df[['Marks']]

    Marks
0    85.0
1    78.0
2    92.0
3    88.0
4    76.0
5    81.0
6     NaN
7    67.0
8    89.0
9    73.0
10   91.0
11   84.0
12   79.0
13   87.0
14   93.0
15   75.0
16   82.0
17   85.0
18    NaN
19   80.0

In [131]:
df

    Student_ID Student_Name  Marks
0          101        Aarav   85.0
1          102       Vivaan   78.0
2          103       Aditya   92.0
3          104      Krishna   88.0
4          105        Arjun   76.0
5          106        Rohan   81.0
6          107        Karan    NaN
7          108        Rahul   67.0
8          109        Mohit   89.0
9          110        Ankit   73.0
10         111        Priya   91.0
11         112         Neha   84.0
12         113          NaN   79.0
13         114        Sneha   87.0
14         115         Riya   93.0
15         116       Simran   75.0
16         117        Kavya   82.0
17         118        Aarav   85.0
18         119          NaN    NaN
19         120        Aditi   80.0

In [132]:
df.duplicated().sum()

np.int64(0)

In [133]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_ID    20 non-null     int64
 1   Student_Name  18 non-null     str
 2   Marks         18 non-null     float64
dtypes: float64(1), int64(1), str(1)
memory usage: 612.0 bytes

In [134]:
df.drop('Student_ID',axis=1, inplace=True)

In [135]:
df

   Student_Name  Marks
0         Aarav   85.0
1        Vivaan   78.0
2        Aditya   92.0
3       Krishna   88.0
4         Arjun   76.0
5         Rohan   81.0
6         Karan    NaN
7         Rahul   67.0
8         Mohit   89.0
9         Ankit   73.0
10        Priya   91.0
11         Neha   84.0
12          NaN   79.0
13        Sneha   87.0
14         Riya   93.0
15       Simran   75.0
16        Kavya   82.0
17        Aarav   85.0
18          NaN    NaN
19        Aditi   80.0

In [136]:
df=pd.read_csv(r'C:\Users\RIya\Desktop\datascience\6month-Data-Science\machine learning\bike project\Data\Used_Bikes.csv')

In [137]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [138]:
df.head()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [139]:
df.tail(10)

,bike_name,price,city,kms_driven,owner,age,power,brand
32638,Yamaha Fazer 25 250cc,123000.0,Kadapa,14500.0,First Owner,4.0,250.0,Yamaha
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield
32640,Hero Passion Pro 100cc,32000.0,Delhi,12000.0,First Owner,6.0,100.0,Hero
32641,Bajaj Avenger 220cc,41000.0,Delhi,20245.0,Second Owner,11.0,220.0,Bajaj
32642,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [140]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [141]:
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='str')

In [142]:
df[['brand']]

               brand
0                TVS
1      Royal Enfield
2            Triumph
3                TVS
4             Yamaha
...              ...
32643           Hero
32644            TVS
32645          Bajaj
32646           Hero
32647          Bajaj

[32648 rows x 1 columns]

In [143]:
df[['price']]

          price
0       35000.0
1      119900.0
2      600000.0
3       65000.0
4       80000.0
...         ...
32643   39000.0
32644   30000.0
32645   60000.0
32646   15600.0
32647   22000.0

[32648 rows x 1 columns]

In [144]:
df[['city']]

            city
0      Ahmedabad
1          Delhi
2          Delhi
3      Bangalore
4      Bangalore
...          ...
32643      Delhi
32644     Karnal
32645      Delhi
32646     Jaipur
32647       Pune

[32648 rows x 1 columns]

In [145]:
df.bike_name

0          TVS Star City Plus Dual Tone 110cc
1                 Royal Enfield Classic 350cc
2                        Triumph Daytona 675R
3                        TVS Apache RTR 180cc
4        Yamaha FZ S V 2.0 150cc-Ltd. Edition
                         ...
32643                  Hero Passion Pro 100cc
32644                    TVS Apache RTR 180cc
32645                Bajaj Avenger Street 220
32646               Hero Super Splendor 125cc
32647                      Bajaj Pulsar 150cc
Name: bike_name, Length: 32648, dtype: str

In [146]:
df.owner

0        First Owner
1        First Owner
2        First Owner
3        First Owner
4        First Owner
            ...
32643    First Owner
32644    First Owner
32645    First Owner
32646    First Owner
32647    First Owner
Name: owner, Length: 32648, dtype: str

In [147]:
df.brand

0                  TVS
1        Royal Enfield
2              Triumph
3                  TVS
4               Yamaha
             ...
32643             Hero
32644              TVS
32645            Bajaj
32646             Hero
32647            Bajaj
Name: brand, Length: 32648, dtype: str

In [148]:
df['owner']

0        First Owner
1        First Owner
2        First Owner
3        First Owner
4        First Owner
            ...
32643    First Owner
32644    First Owner
32645    First Owner
32646    First Owner
32647    First Owner
Name: owner, Length: 32648, dtype: str

In [149]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [150]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [151]:
df['brand'].nunique()

23

In [152]:
df['brand'].nunique()

23

In [153]:
df['brand'].value_counts()

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
LML                    1
Yezdi                  1
Name: count, dtype: int64

In [154]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [155]:
df.duplicated().sum()

np.int64(25324)

In [156]:
df.drop_duplicates()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [157]:
df.duplicated().sum()

np.int64(25324)

In [158]:
df.drop_duplicates(inplace=True)

In [159]:
df.duplicated().sum()

np.int64(0)

In [160]:
df.isnull()

      bike_name  price   city  kms_driven  owner    age  power  brand
0         False  False  False       False  False  False  False  False
1         False  False  False       False  False  False  False  False
2         False  False  False       False  False  False  False  False
3         False  False  False       False  False  False  False  False
4         False  False  False       False  False  False  False  False
...         ...    ...    ...         ...    ...    ...    ...    ...
9362      False  False  False       False  False  False  False  False
9369      False  False  False       False  False  False  False  False
9370      False  False  False       False  False  False  False  False
9371      False  False  False       False  False  False  False  False
9372      False  False  False       False  False  False  False  False

[7324 rows x 8 columns]

In [161]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [162]:
# df.dropna(inplace=True)  ## null value ko drop karne ke liye use hota hai. inplace=True se original dataframe me changes ho jate hai.

In [163]:
df=pd.read_csv(r'C:\Users\RIya\Desktop\datascience\6month-Data-Science\machine learning\bike project\Data\Used_Bikes.csv')

In [164]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [165]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [166]:
owner_dict ={'First Owner':1, 'Second Owner':2, 'Third Owner':3, 'Fourth Owner Or More':4}
df['owner'] = df['owner'].map(owner_dict)

In [167]:
df['owner'].unique()

array([1, 2, 3, 4])

In [168]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,1,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,1,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,1,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,1,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,1,13.0,150.0,Bajaj

In [169]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [170]:
brand_dict={'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':4,            'Hero':5,           'Bajaj':6,          'Suzuki':7,
         'Benelli':8,             'KTM':9,        'Mahindra':10,        'Kawasaki':11,
          'Ducati':12,         'Hyosung':13, 'Harley-Davidson':14,            'Jawa':15,
             'BMW':16,          'Indian':17,         'Rajdoot':18,             'LML':19,
           'Yezdi':20,              'MV':21,           'Ideal':22}
df['brand'] = df['brand'].map(brand_dict)

In [171]:
df['brand'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22])

In [172]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1,3.0,110.0,1
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1,4.0,350.0,2
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1,8.0,675.0,3
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1,4.0,180.0,1
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1,3.0,150.0,4
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,1,4.0,100.0,5
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,1,9.0,180.0,1
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,1,6.0,220.0,6
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,1,16.0,125.0,5
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,1,13.0,150.0,6

In [173]:
df.drop(['bike_name','city'],axis=1,inplace=True)

In [174]:
df

          price  kms_driven  owner   age  power  brand
0       35000.0     17654.0      1   3.0  110.0      1
1      119900.0     11000.0      1   4.0  350.0      2
2      600000.0       110.0      1   8.0  675.0      3
3       65000.0     16329.0      1   4.0  180.0      1
4       80000.0     10000.0      1   3.0  150.0      4
...         ...         ...    ...   ...    ...    ...
32643   39000.0     22000.0      1   4.0  100.0      5
32644   30000.0      6639.0      1   9.0  180.0      1
32645   60000.0     20373.0      1   6.0  220.0      6
32646   15600.0     84186.0      1  16.0  125.0      5
32647   22000.0     60857.0      1  13.0  150.0      6

[32648 rows x 6 columns]

In [175]:
df.drop_duplicates(inplace=True)

In [176]:
df.isnull().sum()

price         0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [177]:
x= df.drop('price',axis=1)

In [178]:
x

      kms_driven  owner  age  power  brand
0        17654.0      1  3.0  110.0      1
1        11000.0      1  4.0  350.0      2
2          110.0      1  8.0  675.0      3
3        16329.0      1  4.0  180.0      1
4        10000.0      1  3.0  150.0      4
...          ...    ...  ...    ...    ...
9362     48587.0      1  8.0  150.0      5
9369     60000.0      1  9.0  220.0      6
9370      3430.0      1  4.0  750.0     14
9371     21300.0      1  4.0  400.0      6
9372      7127.0      1  5.0  220.0      6

[7306 rows x 5 columns]

In [179]:
y= df['price']

In [180]:
y

0        35000.0
1       119900.0
2       600000.0
3        65000.0
4        80000.0
          ...
9362     25000.0
9369     35000.0
9370    450000.0
9371    139000.0
9372     80000.0
Name: price, Length: 7306, dtype: float64

In [181]:
df.to_csv("clean_bike_data.csv")